### PR TITLE
Issue 3: Add ticker

### PR DESCRIPTION
**Pull request by AliakseiKorneu**

### CODE REVIEW

**Comment by IharKrasnik** [comment]
@AliakseiKorneu Awesome job.

**Comment by AliakseiKorneu** [comment]
@IharKrasnik thx, dude!

**Review by IharKrasnik — APPROVED** [review]
Thumbs up!

**Review by andrewnester — APPROVED** [review]

**Comment by andrewnester** [comment]
Great work @AliakseiKorneu , thanks!

**Pull request merged**
